apiVersion: v1
kind: Namespace
metadata:
  name: webpage-operator

---
# 因为operator需要watch crd定义的cr资源对象，需要单独配置访问api server的权限
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webpage-operator
  namespace: webpage-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-operator
  namespace: webpage-operator
spec:
  selector:
    matchLabels:
      app: webpage-operator
  replicas: 1
  template:
    metadata:
      namespace: webpage-operator
      labels:
        app: webpage-operator
    spec:
      serviceAccountName: webpage-operator
      containers:
      - name: operator
        image: webpage-operator:0.0.1
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /startup
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 1
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 2
          failureThreshold: 3

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-admin
subjects:
- kind: ServiceAccount
  name: webpage-operator
  namespace: webpage-operator
roleRef:
  kind: ClusterRole
  name: webpage-operator
  apiGroup: ""

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webpage-operator
rules:
# 解析 custom resource 后需要部署标准对象的权限
- apiGroups:
  - ""
  resources:
  - deployments
  - services
  - configmaps
  - pods
  verbs:
  - '*'
- apiGroups:
  - "apps"
  resources:
  - deployments
  - services
  - configmaps
  verbs:
  - '*'
# watch custom resource的权限
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
# watch custom resource的权限
- apiGroups:
  - "operator.k8s.huang.org"
  resources:
  - webpages
  - webpages/status
  verbs:
  - '*'
# TODO 注册ingress路由的权限，本实验暂时不注册ingress
- apiGroups:
    - "networking.k8s.io"
  resources:
    - ingresses
  verbs:
    - '*'

