apiVersion: "operator.k8s.huang.org/v1"
kind: WebPage
metadata:
# Use labels to match the resource with different reconciler implementations:
# labels:
#    low-level: "true"
  name: hello-operator
spec:
  exposed: false
  html: |
    <html>
      <head>
        <title>Hello Operator World</title>
      </head>
      <body>
        Hello World! 
      </body>
    </html>
